### ISSUE TITLE
TODO

### ISSUE THREAD

**Issue by cjbarrie** [cjbarrie/academictwitteR#107]
The following list outlines multiple enhancements, with check box lists to record progress. 
- [ ] Add unit testing for authorization-required functions
- [ ] Update package citation details
- [ ] Ensure documentation and vignettes consistent esp. with new `get_bearer()` and `set_bearer()` functions
- [ ] The main tweet retrieval functions only return results as data frames when they complete. Data loss is mitigated by specifying data path field to store data as we go, but can we also return a dataframe object or .rds file as well if the function is interrupted or fails?
- [ ] Fix RTs getting cut off in main tweet_ data. Requires re-incorporating full RT text by re-querying these tweet IDs? Could just add an additional convenience function.
- [x] Add functionality for querying conversation_id field
- [ ] Add user handle to data frame automatically (currently stored in user_* return)
- [ ] Incorporate build_user_query into get_user_tweets function
- [ ] Improve rate limiting handling: manual specification of sleep between calls and/or trycatch addition?
- [ ] Add random sample function (see https://twittercommunity.com/t/generating-a-random-set-of-tweet-ids/150255/11 for how to discussion)
