### ISSUE TITLE
Enhancements TODO

### ISSUE THREAD

**Issue by cjbarrie** [cjbarrie/academictwitteR#27]
The following list outlines multiple enhancements, with check box lists to record progress. The name in brackets indicates the dev responsible for each enhancement/change

- [x] Deprecate get_hashtag_tweets and use new function get_all_tweets as foundation (because hashtag queries are recognized as such with "#" before the string query. So can be incorporated into get_all_tweets, which takes both string queries and hashtags. (CHRIS TO DO)

- [x] In get_all_tweets and get_user_tweets functions line : `saveRDS(df.all, file = file)` should be changed to  `saveRDS(df.all, file = file = paste0(file, “.rds”))` so that the user only needs to name the .rds file (rather than e.g. specify `file= "tweets.rds"`) (CHRIS TO DO)
- [x] Add functionality or at least a vignette explainer on how to combine multiple queries e.g. `tweets <- get_all_tweets("(happy OR happiness) place_country:GB place:Manchester -birthday -is:retweet", "2021-01-01T00:00:00Z", "2021-01-01T01:00:00Z",  bearer_token)` (CHRIS TO DO)

- [x] Documentation: add vignette describing the thinking behind how the package delivers data. Is done with large-scale data collection in mind. So encourages data storage as JSONs on the fly, in named folders. But also has options to deliver dataframes etc. Discussion of file naming conventions and data delivery should come first in the vignette explainer. (CHRIS TO DO)

- [ ] Add OR and AND options for hashtag and string queries; i.e., to allow user to request tweets containing both strings or hashtags or either string or hashtag. Details of AND and OR logics here: https://developer.twitter.com/en/docs/twitter-api/tweets/search/integrate/build-a-query. AND is the default when multiple strings specified. Can add an OR option by e.g. taking strings and, when OR is TRUE, calling `paste(strings, collapse = “ OR ”)`. GROUPING logic could also be incorporated. (CHRIS TO DO)
 
- [ ] The main tweet retrieval functions only return results as data frames when they complete. Data loss is, of course, mitigated, by specifying data path field to store data as we go, but can we also return a dataframe object or .rds file as well if the function is interrupted or fails? (JUSTIN TO DO)
  - [x] Another option here is to make a new argument e.g. `bind_json = T` in the main `get_all_tweet` function (and associated functions), which would mean JSONs are only bound if the user specified this. If they specify `bind_json=F` then JSONs will just be generated and not bound into a dataframe. Can then use the convenience binding functions listed below to bind when wanted. Added as `bind_tweets`

- [x] Add a bind JSON convenience function for user and tweet-level information. Useful if stored only as JSONs and user wants to bind into a dataframe after retrieval, or if the data collection is interrupted. (JUSTIN TO DO)

- [x] Add a "get last tweet" convenience function. Useful if data collection is interrupted and they want to recommence retrieval from the last tweet (or user) collected. (JUSTIN TO DO)

- [x] Include standalone functions for has: conjunction-required operators. See https://developer.twitter.com/en/docs/twitter-api/tweets/search/integrate/build-a-query for details. This can be achieved by repurposing the get_all_tweets workhorse functions and adding e.g. `q = paste("has:media" ,query)`. This can be done by creating separate functions for:
  - [x] has:media (`get_media_tweets`)
  - [x] has:mentions (`get_mentions_tweets`)
  - [x] has:images (`get_images_tweets`)
  - [x] has:videos (`get_videos_tweets`)
  - [x] has:geo (`get_geo_tweets`)

- [x] Integrate conjunction-required operators (i.e., from "is:retweet" downwards in this list: https://developer.twitter.com/en/docs/twitter-api/tweets/search/integrate/build-a-query#types) into the main `get_all_tweets` function as arguments. Can be achieved by series of `ifelse()` calls e.g., `imgq <- ifelse(hasimage==T, "has:image ", NULL)` then paste to query with `q <- paste0(imgq, query)`. Other functions for e.g., `get_media_tweets` can remain as "shortcut" functions. (JUSTIN TODO)
 
- [x] Include standalone functions for
  - [x] url: (`get_url_tweets`) TODO: fix the paste() call to get e.g. `'url: "url.com"'` properly specified
  - [x] to: (`get_to_tweets`)
  - [x] retweets_of: (`get_retweets_of_user`)
 
- [x] Add functionality for:
  - [x] place: (`get_place_tweets`)
  - [x] place_country: (`get_country_tweets`)
  - [x] point_radius: (`get_radius_tweets`)
  - [x] bounding_box: (`get_bb_tweets`)
  - [x] langs: (`get_lang_tweets`)
    - [ ] Include convenience function to look up languages?
(CHRIS TO DO)
  
- [ ] ~~Add exclude retweets option with -is:retweet (JUSTIN TO DO)~~

- [ ] ~~Add exclude promoted tweets option with -is:nullcast (JUSTIN TO DO)~~

- [x] Allow negation operators (i.e., when searching for strings but not some strings: e.g., `query = cat #meme -grumpy`) (JUSTIN TO DO)

- [ ] Add bio: and bio_name and has:profile_geo user search functionality to user search function. (JUSTIN TO DO)

- [ ] ~~Add sample: as an option to `get_all_tweets` function. This gives a % random sample (e.g., sample:10 gives 10% sample) rather than all tweets. Useful if retrieved data is likely to be large. Or if testing queries. Details here: https://developer.twitter.com/en/docs/twitter-api/tweets/filtered-stream/integrate/build-a-rule. (JUSTIN TO DO)~~ NOT POSSIBLE WITH FULL ARCHIVE SEARCH

- [ ] ~~Add context: operators to get tweets annotated by particular context. Details here: https://developer.twitter.com/en/docs/twitter-api/tweets/filtered-stream/integrate/build-a-rule.~~
  - [ ] ~~Include also a convenience function that looks up the context and domain entity ids?
(JUSTIN TO DO)~~ NOT POSSIBLE WITH FULL ARCHIVE SEARCH

- [x] Add Zenodo release and obtain DOI. (CHRIS TO DO)
- [ ]  ~~Add functionality for querying conversation_id field~~ NOT POSSIBLE WITH FULL ARCHIVE SEARCH
- [x] Add max. number of tweets argument
- [ ] Add user handle to data.frame automatically
- [ ] Incorporate build_user_query into get_user_tweets function
- [x] Rate limiting handling: manual specification of sleep between calls and/or trycatch addition?
- [ ] Get data in tidy format?
- [ ] Fix RTs getting cut off in main tweet_ data
- [ ] Add random sample function (see https://twittercommunity.com/t/generating-a-random-set-of-tweet-ids/150255/11 for how to discussion)
