### ISSUE TITLE
CRAN Submission TODO

### ISSUE THREAD

**Issue by justinchuntingho** [cjbarrie/academictwitteR#74]
- [x]  Update vignettes (if necessarily)
- [x]  Run `devtools::check_win_release()` and `devtools::check_win_devel()`
- [x]  Update cran-comments.md
- [x]  Submitting using `devtools::release()`
